# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eluser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuse_att', models.PositiveIntegerField(blank=True, null=True)),
                ('enrollment_id', models.CharField(max_length=6)),
                ('comentario', models.TextField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AC', 'Activo'), ('BJ', 'Baja'), ('BN', 'Baja Network'), ('BL', 'Bloqueado'), ('PE', 'Pendiente'), ('RE', 'Rechazado'), ('RS', 'Revisar Estatus')], max_length=2)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('num_imss', models.CharField(max_length=11)),
                ('curp', models.CharField(max_length=18)),
                ('direccion', models.TextField()),
                ('u_fecha_modificacion', models.DateField(auto_now=True)),
                ('u_fecha_creacion', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elusuario', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laempresa', to='Enrollment.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Yasc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('imei', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenrollment2', to='Enrollment.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='enroll',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenrollment', to='Enrollment.Usuario'),
        ),
    ]
