# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AC', 'Activo'), ('BJ', 'Baja'), ('BN', 'Baja Network'), ('BL', 'Bloqueado'), ('PE', 'Pendiente'), ('RE', 'Rechazado'), ('RS', 'Revisar Estatus')], max_length=2)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('num_imss', models.CharField(max_length=20)),
                ('curp', models.CharField(max_length=18)),
                ('direccion', models.TextField()),
                ('u_fecha_modificacion', models.DateField(auto_now=True)),
                ('u_fecha_creacion', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
