# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eluser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuse_att', models.PositiveIntegerField(blank=True, null=True)),
                ('enrollment_id', models.CharField(max_length=6)),
                ('comentario', models.TextField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc3_alturas', models.DateField(blank=True, null=True)),
                ('dc3_escaleras', models.DateField(blank=True, null=True)),
                ('dc3_riesgos_electricos', models.DateField(blank=True, null=True)),
                ('primeros_auxilios', models.DateField(blank=True, null=True)),
                ('certificado_medico', models.DateField(blank=True, null=True)),
                ('arnes', models.DateField(blank=True, null=True)),
                ('bandola', models.DateField(blank=True, null=True)),
                ('linea_vida', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AC', 'Activo'), ('BJ', 'Baja'), ('BL', 'Bloqueado'), ('PR', 'En Proceso')], max_length=2)),
                ('status_operaciones', models.CharField(choices=[('OP', 'Operativo'), ('SP', 'En Espera De Asignación')], max_length=2)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=200)),
                ('num_imss', models.CharField(max_length=11)),
                ('curp', models.CharField(max_length=18)),
                ('direccion', models.TextField()),
                ('cargo', models.CharField(choices=[('AD', 'Administrativo'), ('CO', 'Coordinador'), ('LI', 'Líder'), ('PM', 'PM'), ('SP', 'Supervisor'), ('TC', 'Técnico')], max_length=2)),
                ('actividades', models.TextField()),
                ('fecha_liberado_ehs', models.DateField(blank=True, null=True)),
                ('u_fecha_modificacion', models.DateField(auto_now=True)),
                ('u_fecha_creacion', models.DateField(auto_now_add=True)),
                ('elusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laempresa', to='Enrollment.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Yasc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('imei', models.CharField(blank=True, max_length=17, null=True)),
                ('pac_blu', models.DateField()),
                ('email', models.CharField(max_length=60)),
                ('comentario', models.TextField()),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enrollment.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='epp',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enrollment.Usuario'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enrollment.Usuario'),
        ),
    ]
