# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0002_yasc_capturado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('AD', 'Administrativo'), ('CO', 'Coordinador'), ('LI', 'Líder'), ('PM', 'PM'), ('SP', 'Supervisor'), ('TC', 'Técnico')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status_operaciones',
            field=models.CharField(blank=True, choices=[('OP', 'Operativo'), ('SP', 'En Espera De Asignación')], max_length=2, null=True),
        ),
    ]
