# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0002_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elusuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laempresa', to='Enrollment.Empresa'),
        ),
    ]
