# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0002_auto_20170802_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yasc',
            old_name='email',
            new_name='email_pac_blu',
        ),
    ]
