# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0003_auto_20170722_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuse_att', models.PositiveIntegerField(blank=True, null=True)),
                ('enrollment_id', models.CharField(max_length=6)),
                ('comentario', models.TextField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenrollment', to='Enrollment.Usuario')),
            ],
        ),
    ]
