# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0004_enrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Enroll',
        ),
    ]
