# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0005_auto_20170723_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='num_imss',
            field=models.CharField(max_length=11),
        ),
    ]
