# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0006_auto_20170723_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yasc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenrollment2', to='Enrollment.Usuario')),
            ],
        ),
    ]
