# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0007_yasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yasc',
            name='imei',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
